function R = get_rotation_zyx(phi,theta,psi)
% Return rotation matrix for ZYX Euler angles (Tait-Bryan angles)
    R_x = [1    0       0; ...
           0  cos(phi) -sin(phi); ...
           0  sin(phi) cos(phi)];
       
    R_y = [cos(theta)  0   sin(theta); ...
           0           1         0; ...
          -sin(theta) 0   cos(theta)]; 
       
    R_z = [cos(psi) -sin(psi)  0; ...
           sin(psi)  cos(psi)  0; ...
           0           0       1];  
    R = R_z*R_y*R_x;
end